spring:
  application:
    name: drools-senior

#kieserver:
#https://docs.jboss.org/drools/release/7.42.0.Final/drools-docs/html_single/index.html#_spring_boot_configuration

#是否启用taskAssigning
kieserver:
  taskAssigning:
    runtime:
      enabled: true

#启用taskAssigning后，账户密码和连接信息
taskassigning:
  processRuntime:
    url: http://192.168.50.44:8180/kie-server/services/rest/server
    user: kieserver
    pwd: kieserver1!