//// 规则包需要可kmodule文件下kbase的packages属性保持，否则读取不到
//package demo1
//
//// 导入类
//import com.laher.drools.entity.Order
//import com.laher.drools.entity.Item
//
//// 相同类型的产品满足200减30优惠
//// 规则名称，不可重复
//rule favourableActivity
//when
//    // 条件：存在Customer对象（Customer不为空）
//    // 条件：消费金额大于0并且小于200
////    $o:Order() from accumulate(Item($money:money),sum($money))
////    $items:Item() from $o.items
////    $s : Order() from
////    accumulate( Item( $temp : money );
////                $max : max( $temp ),
////                $avg : average( $temp );
////                $min < 20, $avg > 70 )
//    $o:Order() //from accumulate(Item($item:$o.items))
//    $total:Integer(doubleValue()>100) from accumulate (Item($money:money),sum($money))
//
//then
//    // 满足条件执行操作
//    System.out.println($total);
////    $o.setPreferentialMoney(30);
////    $o.setActualMoney($o.getMoney()-$o.getPreferentialMoney());
//end